export const endpoints = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
  },
  users: {
    me: "/users/me",
  },
  leads: {
    create: "/leads",
    list: "/leads",
    detail: (id: string) => `/leads/${id}`,
    reply: (id: string) => `/leads/${id}/reply`,
  },
  calls: {
    slots: "/calls/slots",
    create: "/calls",
    list: "/calls",
    detail: (id: string) => `/calls/${id}`,
    availability: "/calls/availability",
    manage: (token: string) => `/calls/manage/${token}`,
    cancel: (token: string) => `/calls/manage/${token}/cancel`,
    reschedule: (token: string) => `/calls/manage/${token}/reschedule`,
  },
  marketplace: {
    list: "/marketplace",
    stats: "/marketplace/stats",
    facets: "/marketplace/facets",
    detail: (id: number | string) => `/marketplace/${id}`,
  },
  orders: {
    checkoutIntent: "/orders/checkout-intent",
    me: "/orders/me",
    meDetail: (id: string) => `/orders/me/${id}`,
    confirmPayment: (id: string) => `/orders/me/${id}/confirm-payment`,
    cancel: (id: string) => `/orders/me/${id}/cancel`,
    list: "/orders",
    detail: (id: string) => `/orders/${id}`,
    status: (id: string) => `/orders/${id}/status`,
  },
    reviews: {
    list: "/reviews",
    me: "/reviews/me",
    create: "/reviews",
    admin: "/reviews/admin",
    adminDetail: (id: string) => `/reviews/admin/${id}`,
  },
  promos: {
    list: "/promos",
    detail: (id: string) => `/promos/${id}`,
  },
  health: "/health",
} as const;
