import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { Order } from "@/types/order";
import { formatCents, statusLabel } from "@/lib/orders-ui";
import { siteConfig } from "@/config/site";

export function downloadOrderPdf(order: Order) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const marginX = 48;
  let y = 56;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(7, 27, 61);
  doc.text(siteConfig.name, marginX, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("Order invoice", marginX, y + 16);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(7, 27, 61);
  doc.text(order.orderNumber, 547, y, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(new Date(order.createdAt).toLocaleString(), 547, y + 16, {
    align: "right",
  });

  y += 48;
  doc.setDrawColor(226, 232, 240);
  doc.line(marginX, y, 547, y);
  y += 28;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(7, 27, 61);
  doc.text("Bill to", marginX, y);
  doc.text("Status", 320, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);
  const billLines = [
    order.billingName,
    order.billingEmail,
    order.billingPhone,
    order.addressLine1,
    [order.city, order.state, order.postalCode].filter(Boolean).join(", "),
    order.country,
  ].filter(Boolean);

  billLines.forEach((line, i) => {
    doc.text(String(line), marginX, y + 16 + i * 14);
  });

  doc.setFont("helvetica", "bold");
  doc.text(statusLabel(order.status), 320, y + 16);
  doc.setFont("helvetica", "normal");
  doc.text(`Payment: ${order.paymentStatus}`, 320, y + 30);

  y += 16 + billLines.length * 14 + 24;

  autoTable(doc, {
    startY: y,
    head: [["Item", "Service", "Qty", "Unit", "Total"]],
    body: order.items.map((item) => [
      item.domain,
      item.serviceType === "GUEST" ? "Guest post" : "Link insert",
      String(item.quantity),
      formatCents(item.unitPriceCents, order.currency),
      formatCents(item.lineTotalCents, order.currency),
    ]),
    styles: {
      font: "helvetica",
      fontSize: 9,
      cellPadding: 8,
      textColor: [51, 65, 85],
    },
    headStyles: {
      fillColor: [7, 27, 61],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: marginX, right: marginX },
  });

  const finalY =
    (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable
      ?.finalY ?? y + 80;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(7, 27, 61);
  doc.text("Total", 400, finalY + 28);
  doc.text(formatCents(order.totalCents, order.currency), 547, finalY + 28, {
    align: "right",
  });

  if (order.notes) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Notes: ${order.notes}`, marginX, finalY + 52, {
      maxWidth: 500,
    });
  }

  doc.setFontSize(8);
  doc.text(
    `Generated by ${siteConfig.name} · ${new Date().toLocaleString()}`,
    marginX,
    812,
  );

  doc.save(`${order.orderNumber}.pdf`);
}
