export type SiteListing = {
  id: number;
  domain: string;
  niche: string;
  da: number;
  dr: number;
  traffic: number;
  country: string;
  maxDofollow: number;
  guest: number;
  insert: number;
  tat: string;
  owner: "Admin" | "Partner";
  trend: "Rising" | "Stable";
};

export const SITE_LISTINGS: SiteListing[] = [
  {
    id: 1,
    domain: "pyarkishayari.com",
    niche: "General",
    da: 40,
    dr: 67,
    traffic: 29700,
    country: "India",
    maxDofollow: 2,
    guest: 70,
    insert: 60,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 2,
    domain: "suvicharwala.org",
    niche: "General",
    da: 40,
    dr: 66,
    traffic: 6400,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 3,
    domain: "igcoolbio.com",
    niche: "General",
    da: 35,
    dr: 29,
    traffic: 27600,
    country: "India",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 4,
    domain: "mybio4insta.com",
    niche: "General",
    da: 40,
    dr: 70,
    traffic: 9100,
    country: "India",
    maxDofollow: 2,
    guest: 65,
    insert: 55,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 5,
    domain: "instawalebio.com",
    niche: "General",
    da: 40,
    dr: 70,
    traffic: 12500,
    country: "India",
    maxDofollow: 2,
    guest: 65,
    insert: 55,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 6,
    domain: "heartfullines.com",
    niche: "General",
    da: 40,
    dr: 37,
    traffic: 26300,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 7,
    domain: "suvicharpadhe.com",
    niche: "General",
    da: 40,
    dr: 69,
    traffic: 7500,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 8,
    domain: "hindilyricsong.com",
    niche: "General",
    da: 42,
    dr: 58,
    traffic: 12800,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 9,
    domain: "tareefshayari.com",
    niche: "General",
    da: 40,
    dr: 57,
    traffic: 26200,
    country: "India",
    maxDofollow: 2,
    guest: 65,
    insert: 55,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 10,
    domain: "namezcrafter.com",
    niche: "General",
    da: 40,
    dr: 71,
    traffic: 1400,
    country: "USA",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 11,
    domain: "allbuzz.co.uk",
    niche: "News/General",
    da: 44,
    dr: 59,
    traffic: 1000,
    country: "USA",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 12,
    domain: "pandaexpress-menuprices.com",
    niche: "Food/General",
    da: 40,
    dr: 69,
    traffic: 2200,
    country: "USA",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 13,
    domain: "rtischeduler.net",
    niche: "SaaS/General",
    da: 39,
    dr: 67,
    traffic: 1000,
    country: "USA",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 14,
    domain: "womginx.net",
    niche: "SaaS/General",
    da: 44,
    dr: 59,
    traffic: 2200,
    country: "USA",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 15,
    domain: "mcdomenuprices.co.uk",
    niche: "Food/General",
    da: 40,
    dr: 66,
    traffic: 44800,
    country: "UK",
    maxDofollow: 2,
    guest: 75,
    insert: 65,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 16,
    domain: "mcdonaldsmenu.co.uk",
    niche: "Food/General",
    da: 44,
    dr: 68,
    traffic: 1000,
    country: "UK",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 17,
    domain: "punnycaptions.com",
    niche: "General",
    da: 42,
    dr: 35,
    traffic: 1000,
    country: "USA",
    maxDofollow: 2,
    guest: 45,
    insert: 35,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 18,
    domain: "celebpeaks.com",
    niche: "General",
    da: 42,
    dr: 36,
    traffic: 1000,
    country: "USA",
    maxDofollow: 2,
    guest: 45,
    insert: 35,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 19,
    domain: "punwish.com",
    niche: "General",
    da: 42,
    dr: 37,
    traffic: 1000,
    country: "USA",
    maxDofollow: 2,
    guest: 45,
    insert: 35,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 20,
    domain: "keyboardemojis.com",
    niche: "General",
    da: 43,
    dr: 50,
    traffic: 62100,
    country: "Indonesia",
    maxDofollow: 2,
    guest: 75,
    insert: 65,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 21,
    domain: "jollibeemenuprice.net",
    niche: "General",
    da: 43,
    dr: 51,
    traffic: 3400,
    country: "Philippines",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 22,
    domain: "shayarilab.com",
    niche: "General",
    da: 43,
    dr: 36,
    traffic: 55700,
    country: "India",
    maxDofollow: 2,
    guest: 70,
    insert: 60,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 23,
    domain: "motivation-shayari.com",
    niche: "Food/General",
    da: 43,
    dr: 36,
    traffic: 42100,
    country: "India",
    maxDofollow: 2,
    guest: 65,
    insert: 55,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 24,
    domain: "marathiwala.org",
    niche: "General",
    da: 43,
    dr: 36,
    traffic: 40300,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 25,
    domain: "biosafar.com",
    niche: "General",
    da: 44,
    dr: 38,
    traffic: 6000,
    country: "India",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 26,
    domain: "infohindime.com",
    niche: "General",
    da: 44,
    dr: 58,
    traffic: 36000,
    country: "India",
    maxDofollow: 2,
    guest: 70,
    insert: 60,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 27,
    domain: "latestbiodeas.com",
    niche: "General",
    da: 42,
    dr: 35,
    traffic: 23900,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 28,
    domain: "attitudeshayarisudhari.com",
    niche: "General",
    da: 42,
    dr: 40,
    traffic: 14200,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 29,
    domain: "dailydarshantime.com",
    niche: "General",
    da: 42,
    dr: 37,
    traffic: 1000,
    country: "India",
    maxDofollow: 2,
    guest: 45,
    insert: 35,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 30,
    domain: "increaseimgsize.com",
    niche: "General",
    da: 43,
    dr: 35,
    traffic: 18100,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 31,
    domain: "muslimdreams.info",
    niche: "General",
    da: 43,
    dr: 35,
    traffic: 2600,
    country: "India",
    maxDofollow: 2,
    guest: 45,
    insert: 35,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 32,
    domain: "shayari-diary.com",
    niche: "General",
    da: 43,
    dr: 38,
    traffic: 16100,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 33,
    domain: "instagrambio.gen.in",
    niche: "General",
    da: 42,
    dr: 58,
    traffic: 20900,
    country: "India",
    maxDofollow: 2,
    guest: 65,
    insert: 55,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 34,
    domain: "instabioz.in",
    niche: "General",
    da: 43,
    dr: 58,
    traffic: 62100,
    country: "India",
    maxDofollow: 2,
    guest: 80,
    insert: 70,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 35,
    domain: "englishshayarii.com",
    niche: "General",
    da: 43,
    dr: 55,
    traffic: 53400,
    country: "India",
    maxDofollow: 2,
    guest: 75,
    insert: 65,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 36,
    domain: "lyricssongnet.com",
    niche: "General",
    da: 53,
    dr: 55,
    traffic: 47100,
    country: "India",
    maxDofollow: 2,
    guest: 75,
    insert: 65,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 37,
    domain: "ourshayari.com",
    niche: "General",
    da: 42,
    dr: 55,
    traffic: 10700,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 38,
    domain: "shayarana.in",
    niche: "General",
    da: 43,
    dr: 51,
    traffic: 18800,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 39,
    domain: "zeeshayari.com",
    niche: "General",
    da: 54,
    dr: 55,
    traffic: 8100,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 40,
    domain: "mybestbios.net",
    niche: "General",
    da: 61,
    dr: 55,
    traffic: 3000,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 41,
    domain: "achicollection.com",
    niche: "General",
    da: 59,
    dr: 55,
    traffic: 13400,
    country: "India",
    maxDofollow: 2,
    guest: 65,
    insert: 55,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 42,
    domain: "akshayari.com.in",
    niche: "General",
    da: 59,
    dr: 47,
    traffic: 16400,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 43,
    domain: "pyaribaate.in",
    niche: "General",
    da: 42,
    dr: 47,
    traffic: 11200,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 44,
    domain: "myattitudeshayari.com",
    niche: "General",
    da: 41,
    dr: 47,
    traffic: 18800,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 45,
    domain: "ankitshayari.com",
    niche: "General",
    da: 38,
    dr: 37,
    traffic: 4800,
    country: "India",
    maxDofollow: 2,
    guest: 45,
    insert: 35,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 46,
    domain: "trushayari.com",
    niche: "General",
    da: 42,
    dr: 52,
    traffic: 8800,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 47,
    domain: "shayaritouch.com",
    niche: "General",
    da: 43,
    dr: 54,
    traffic: 1000,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 48,
    domain: "sadshayarizone.com",
    niche: "General",
    da: 41,
    dr: 52,
    traffic: 12200,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 49,
    domain: "profactsbd.com",
    niche: "General",
    da: 42,
    dr: 57,
    traffic: 12800,
    country: "Bangladesh",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 50,
    domain: "weblogbd.com",
    niche: "General",
    da: 43,
    dr: 52,
    traffic: 2900,
    country: "Bangladesh",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 51,
    domain: "ultimatequotes.in",
    niche: "General",
    da: 42,
    dr: 58,
    traffic: 16200,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 52,
    domain: "oledsaver.com",
    niche: "General",
    da: 42,
    dr: 54,
    traffic: 1400,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 53,
    domain: "shayaripadhe.com",
    niche: "General",
    da: 36,
    dr: 54,
    traffic: 1400,
    country: "India",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 54,
    domain: "mehndigallery.in",
    niche: "General",
    da: 42,
    dr: 47,
    traffic: 10200,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Rising",
  },
  {
    id: 55,
    domain: "papashayari.in",
    niche: "General",
    da: 42,
    dr: 51,
    traffic: 5300,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 56,
    domain: "stylishnamepro.com",
    niche: "General",
    da: 42,
    dr: 57,
    traffic: 8400,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 57,
    domain: "myinstabio.com",
    niche: "General",
    da: 42,
    dr: 57,
    traffic: 2100,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 58,
    domain: "shayarinow.com",
    niche: "General",
    da: 43,
    dr: 54,
    traffic: 1000,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 59,
    domain: "mytrendingposts.org",
    niche: "General",
    da: 41,
    dr: 51,
    traffic: 4700,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 60,
    domain: "sushiromenusg.org",
    niche: "General",
    da: 42,
    dr: 52,
    traffic: 1000,
    country: "Singapore",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 61,
    domain: "parivahansewass.co",
    niche: "General",
    da: 42,
    dr: 51,
    traffic: 4300,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 62,
    domain: "cashstarkcom.in",
    niche: "General",
    da: 44,
    dr: 62,
    traffic: 2500,
    country: "India",
    maxDofollow: 2,
    guest: 60,
    insert: 50,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 63,
    domain: "nsfollowers.in",
    niche: "General",
    da: 34,
    dr: 54,
    traffic: 1400,
    country: "India",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 64,
    domain: "galibkishayari.in",
    niche: "General",
    da: 43,
    dr: 52,
    traffic: 1800,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 65,
    domain: "kaku-press.com",
    niche: "General",
    da: 42,
    dr: 51,
    traffic: 8700,
    country: "Ethiopia",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 66,
    domain: "fappeningblog.org",
    niche: "General",
    da: 35,
    dr: 50,
    traffic: 4500,
    country: "India",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 67,
    domain: "azsuvichar.com",
    niche: "General",
    da: 42,
    dr: 61,
    traffic: 230,
    country: "India",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 68,
    domain: "shayari.gen.in",
    niche: "General",
    da: 42,
    dr: 39,
    traffic: 860,
    country: "India",
    maxDofollow: 2,
    guest: 45,
    insert: 35,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 69,
    domain: "cutedpimages.com",
    niche: "General",
    da: 42,
    dr: 43,
    traffic: 309,
    country: "India",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 70,
    domain: "mehndidesignz.in",
    niche: "General",
    da: 42,
    dr: 47,
    traffic: 77,
    country: "India",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 71,
    domain: "dailyaxis.co.uk",
    niche: "General",
    da: 42,
    dr: 61,
    traffic: 108,
    country: "UK",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 72,
    domain: "andisearch.in",
    niche: "General",
    da: 42,
    dr: 51,
    traffic: 35,
    country: "India",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 73,
    domain: "shayariblix.in",
    niche: "General",
    da: 43,
    dr: 51,
    traffic: 29,
    country: "India",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 74,
    domain: "shayrihubs.com",
    niche: "General",
    da: 42,
    dr: 51,
    traffic: 64,
    country: "India",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 75,
    domain: "filmyhitblog.in",
    niche: "General",
    da: 35,
    dr: 14,
    traffic: 549,
    country: "India",
    maxDofollow: 2,
    guest: 35,
    insert: 25,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 76,
    domain: "newshungama.com",
    niche: "General",
    da: 31,
    dr: 23,
    traffic: 177,
    country: "Philippines",
    maxDofollow: 2,
    guest: 40,
    insert: 30,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 77,
    domain: "pinterestsaver.in",
    niche: "General",
    da: 42,
    dr: 45,
    traffic: 473,
    country: "India",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 78,
    domain: "ktonlinelogin.my",
    niche: "General",
    da: 28,
    dr: 42,
    traffic: 901,
    country: "Malaysia",
    maxDofollow: 2,
    guest: 45,
    insert: 35,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 79,
    domain: "blessingsvibes.com",
    niche: "General",
    da: 42,
    dr: 41,
    traffic: 225,
    country: "USA",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 80,
    domain: "partnermeaning.com",
    niche: "General",
    da: 42,
    dr: 61,
    traffic: 316,
    country: "USA",
    maxDofollow: 2,
    guest: 55,
    insert: 45,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 81,
    domain: "horizonspheres.com",
    niche: "General",
    da: 7,
    dr: 13,
    traffic: 298,
    country: "USA",
    maxDofollow: 2,
    guest: 25,
    insert: 20,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 82,
    domain: "kfcmenuprice.au",
    niche: "General",
    da: 41,
    dr: 51,
    traffic: 140,
    country: "Australia",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 83,
    domain: "netwyman-blogs.com",
    niche: "General",
    da: 31,
    dr: 21,
    traffic: 377,
    country: "Australia",
    maxDofollow: 2,
    guest: 35,
    insert: 25,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 84,
    domain: "photosqueen.org",
    niche: "General",
    da: 42,
    dr: 26,
    traffic: 5,
    country: "India",
    maxDofollow: 2,
    guest: 40,
    insert: 30,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 85,
    domain: "earn-tuffer.com",
    niche: "General",
    da: 36,
    dr: 11,
    traffic: 57,
    country: "India",
    maxDofollow: 2,
    guest: 35,
    insert: 25,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 86,
    domain: "camillemonfort.com",
    niche: "General",
    da: 42,
    dr: 50,
    traffic: 107,
    country: "USA",
    maxDofollow: 2,
    guest: 50,
    insert: 40,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 87,
    domain: "fastjobmedia.com",
    niche: "General",
    da: 35,
    dr: 14,
    traffic: 247,
    country: "India",
    maxDofollow: 2,
    guest: 35,
    insert: 25,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 88,
    domain: "photoslist.org",
    niche: "General",
    da: 1,
    dr: 15,
    traffic: 5,
    country: "India",
    maxDofollow: 2,
    guest: 25,
    insert: 20,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 89,
    domain: "showbizztodays.com",
    niche: "General",
    da: 37,
    dr: 6,
    traffic: 16,
    country: "UK",
    maxDofollow: 2,
    guest: 30,
    insert: 20,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 90,
    domain: "asianpinay.blog",
    niche: "General",
    da: 35,
    dr: 12,
    traffic: 39,
    country: "Philippines",
    maxDofollow: 2,
    guest: 35,
    insert: 25,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 91,
    domain: "sumosearchs.com",
    niche: "General",
    da: 33,
    dr: 20,
    traffic: 5,
    country: "USA",
    maxDofollow: 2,
    guest: 35,
    insert: 25,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 92,
    domain: "hoptravelers.com",
    niche: "General",
    da: 33,
    dr: 28,
    traffic: 25,
    country: "Russia",
    maxDofollow: 2,
    guest: 40,
    insert: 30,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 93,
    domain: "sportsguruproo.com",
    niche: "General",
    da: 37,
    dr: 25,
    traffic: 0,
    country: "India",
    maxDofollow: 2,
    guest: 40,
    insert: 30,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 94,
    domain: "naz-tricks.com",
    niche: "General",
    da: 37,
    dr: 32,
    traffic: 3,
    country: "India",
    maxDofollow: 2,
    guest: 45,
    insert: 35,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 95,
    domain: "techguescom.com",
    niche: "General",
    da: 37,
    dr: 42,
    traffic: 185,
    country: "India",
    maxDofollow: 2,
    guest: 45,
    insert: 35,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 96,
    domain: "run-post.com",
    niche: "General",
    da: 37,
    dr: 9,
    traffic: 0,
    country: "India",
    maxDofollow: 2,
    guest: 35,
    insert: 25,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 97,
    domain: "blogsternations.com",
    niche: "General",
    da: 43,
    dr: 27,
    traffic: 80,
    country: "USA",
    maxDofollow: 2,
    guest: 40,
    insert: 30,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
  {
    id: 98,
    domain: "nextexamtak.org",
    niche: "General",
    da: 35,
    dr: 1,
    traffic: 38,
    country: "India",
    maxDofollow: 2,
    guest: 30,
    insert: 20,
    tat: "Instant",
    owner: "Admin",
    trend: "Stable",
  },
];

export const MARKETPLACE_FILTERS = [
  { key: "all", icon: "✦", label: "All sites", sub: "Full inventory" },
  { key: "budget", icon: "$", label: "Under $50", sub: "Budget picks" },
  { key: "authority", icon: "◇", label: "DR 40–60", sub: "Authority sites" },
  { key: "traffic", icon: "↗", label: "Traffic 10K+", sub: "High traffic" },
  { key: "India", icon: "◆", label: "India", sub: "India traffic" },
  { key: "General", icon: "⌘", label: "General", sub: "General niche" },
  { key: "highDa", icon: "✓", label: "DA 50+", sub: "High authority" },
] as const;

export type FilterKey = (typeof MARKETPLACE_FILTERS)[number]["key"];

export const SORT_OPTIONS = [
  { value: "recommended", label: "Recommended" },
  { value: "price", label: "Price: Low to high" },
  { value: "traffic", label: "Highest traffic" },
  { value: "dr", label: "Highest DR" },
  { value: "da", label: "Highest DA" },
] as const;

export const HERO_TRUST = [
  "No hidden fees",
  "7-day replacement",
  "Live URL reports",
] as const;

export const HERO_STATS = [
  { value: "98", suffix: "", label: "Verified websites", countTo: 98, duration: 1.6 },
  { value: "10", suffix: "+", label: "Traffic countries", countTo: 10, duration: 1.2 },
  { value: "Instant", suffix: "", label: "Publish TAT", countTo: null, duration: 0 },
  { value: "2", suffix: "", label: "Max dofollow links", countTo: 2, duration: 1.0 },
] as const;

export const BENEFITS = [
  {
    icon: "◉",
    title: "Direct & trusted inventory",
    description:
      "Admin-controlled and vetted partner websites with clear placement histories.",
  },
  {
    icon: "↯",
    title: "Fast order processing",
    description: "Clear turnaround times and a streamlined campaign approval flow.",
  },
  {
    icon: "♢",
    title: "Replacement assurance",
    description: "A defined replacement policy if an eligible link is removed.",
  },
  {
    icon: "▤",
    title: "One live report",
    description: "URLs, anchor text, target pages, costs, and status in one place.",
  },
] as const;

export const AGENCY_PERKS = [
  "Reseller-friendly bulk pricing",
  "Dedicated campaign manager",
  "White-label placement reports",
  "Private inventory on request",
] as const;

export const AGENCY_METRICS = [
  { label: "Live placements", value: "48" },
  { label: "Avg. TAT", value: "Instant" },
  { label: "On-time", value: "96%" },
] as const;

export const AGENCY_CHART_BARS = [
  {
    height: 44,
    label: "Mon",
    value: "32",
    unit: "live",
    hint: "Monday — 32 placements went live across agency accounts.",
  },
  {
    height: 62,
    label: "Tue",
    value: "41",
    unit: "live",
    hint: "Tuesday — steady fulfillment with 41 published links.",
  },
  {
    height: 51,
    label: "Wed",
    value: "36",
    unit: "live",
    hint: "Wednesday — mid-week volume held at 36 live placements.",
  },
  {
    height: 78,
    label: "Thu",
    value: "52",
    unit: "live",
    hint: "Thursday — peak publishing day with 52 links delivered.",
  },
  {
    height: 70,
    label: "Fri",
    value: "47",
    unit: "live",
    hint: "Friday — 47 placements completed before weekend handoff.",
  },
  {
    height: 92,
    label: "Sat",
    value: "61",
    unit: "live",
    hint: "Saturday — highest output this week: 61 live URLs.",
  },
  {
    height: 83,
    label: "Sun",
    value: "55",
    unit: "live",
    hint: "Sunday — strong close with 55 placements reported.",
  },
] as const;

export const PROCESS_STEP_KEYS = ["01", "02", "03", "04"] as const;

export const PROCESS_STEPS = [
  {
    step: "01",
    title: "Filter or share your brief",
    description:
      "Choose placements yourself or tell us your niche, traffic and budget targets.",
  },
  {
    step: "02",
    title: "Approve your shortlist",
    description: "Review metrics, pricing, content rules, and turnaround expectations.",
  },
  {
    step: "03",
    title: "We publish",
    description: "Our team coordinates content and publishing with every selected website.",
  },
  {
    step: "04",
    title: "Receive your report",
    description: "Get the live URL and campaign details in one client-ready report.",
  },
] as const;

export const FAQ_KEYS = ["verified", "dofollow", "niches", "discounts"] as const;

export const FAQ_ITEMS = [
  {
    question: "How are websites and traffic verified?",
    answer:
      "Inventory is reviewed for organic visibility, traffic trend, editorial quality, outbound-link patterns, and publishing history. The final production site should connect these values to your live verification process.",
  },
  {
    question: "Are the links permanent and dofollow?",
    answer:
      "This prototype demonstrates where policy details and buying objections will be answered clearly before checkout.",
  },
  {
    question: "Can I order casino, crypto or CBD placements?",
    answer:
      "This prototype demonstrates where policy details and buying objections will be answered clearly before checkout.",
  },
  {
    question: "Do you provide content and bulk discounts?",
    answer:
      "This prototype demonstrates where policy details and buying objections will be answered clearly before checkout.",
  },
] as const;

export const CTA_NICHES = [
  "General",
  "Food/General",
  "News/General",
  "SaaS/General",
] as const;

export const CTA_BUDGETS = ["$30–$50", "$50–$100", "$100+"] as const;

export const HERO_PREVIEW_ROWS = [
  {
    initials: "IB",
    domain: "instabioz.in",
    meta: "General · India",
    dr: "58",
    traffic: "62.1K",
    price: "$80",
    featured: true,
    purple: false,
  },
  {
    initials: "KE",
    domain: "keyboardemojis.com",
    meta: "General · Indonesia",
    dr: "50",
    traffic: "62.1K",
    price: "$75",
    featured: false,
    purple: true,
  },
] as const;

export function formatTraffic(value: number): string {
  if (value >= 1000) {
    const k = value / 1000;
    return `${k % 1 === 0 ? k.toFixed(0) : k.toFixed(1)}K`;
  }
  return String(value);
}

export function domainInitials(domain: string): string {
  return domain
    .replace(/\.(co\.uk|com\.au|gen\.in|com\.in|org|net|info|blog|co|in|com|au|my)$/i, "")
    .split(/(?=[A-Z])|[-_.]/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? "")
    .join("");
}

export const COUNTRY_FLAGS: Record<string, string> = {
  India: "🇮🇳",
  USA: "🇺🇸",
  UK: "🇬🇧",
  Indonesia: "🇮🇩",
  Philippines: "🇵🇭",
  Bangladesh: "🇧🇩",
  Singapore: "🇸🇬",
  Ethiopia: "🇪🇹",
  Malaysia: "🇲🇾",
  Australia: "🇦🇺",
  Russia: "🇷🇺",
};
